#!/usr/bin/env python3
"""Exercise Codex context cleanup through real fresh and repeated installs."""
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parent.parent


class CodexInstallTests(unittest.TestCase):
    def test_install_and_repeat_preserve_project_context(self):
        with tempfile.TemporaryDirectory(prefix='harness codex ') as tmp:
            root = Path(tmp)
            project = root / 'project with spaces'
            project.mkdir()
            binaries = root / 'bin'
            binaries.mkdir()
            bd = binaries / 'bd'
            bd.write_text('''#!/usr/bin/env python3
import json,sys
from pathlib import Path
if sys.argv[1:4] == ['config','get','issue_prefix']:
    print('fixture')
elif sys.argv[1] == 'init':
    Path('.beads').mkdir(exist_ok=True)
    with Path('AGENTS.md').open('a') as f:
        f.write('\\n<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->\\nbd prime\\n<!-- END BEADS CODEX SETUP -->\\n')
    p=Path('.codex/hooks.json')
    p.parent.mkdir(exist_ok=True)
    p.write_text(json.dumps({'hooks':{
        'SessionStart':[{'matcher':'startup','hooks':[
            {'type':'command','command':'bd codex-hook SessionStart'},
            {'type':'command','command':'echo local-start'}]}],
        'PostCompact':[{'hooks':[{'type':'command','command':'bd codex-hook PostCompact'}]}],
        'UserPromptSubmit':[{'hooks':[{'type':'command','command':'bd codex-hook UserPromptSubmit'}]}],
        'Stop':[{'hooks':[{'type':'command','command':'echo local-stop'}]}]}}))
''')
            bd.chmod(0o755)
            env = {**os.environ, 'PATH': str(binaries) + os.pathsep + os.environ['PATH']}
            def install():
                subprocess.run(['bash', str(ROOT / 'commands/add.sh'), str(project)],
                               env=env, check=True, capture_output=True, text=True)
            install()
            hooks_path = project / '.codex/hooks.json'
            hooks = json.loads(hooks_path.read_text())['hooks']
            commands = [h['command'] for groups in hooks.values() for g in groups for h in g['hooks']]
            self.assertFalse(any('bd codex-hook' in c or 'bd prime' in c for c in commands))
            self.assertIn('echo local-start', commands)
            self.assertIn('echo local-stop', commands)
            brief = [c for c in commands if 'scripts/brief.sh' in c]
            self.assertEqual(len(brief), 1)
            self.assertNotIn('BEGIN BEADS', (project / 'AGENTS.md').read_text())
            self.assertIn('harness/codex.md', (project / 'AGENTS.md').read_text())
            self.assertIn('local commits without another user request', (project / 'harness/codex.md').read_text())
            beads = (project / '.claude/skills/beads/SKILL.md').read_text()
            self.assertNotIn('\nbd prime\n', beads)
            self.assertNotIn('or mutate tasks', beads)
            self.assertIn('--status open', (project / '.claude/skills/handoff/SKILL.md').read_text())
            before = hooks_path.read_bytes()
            install()
            self.assertEqual(before, hooks_path.read_bytes())
            # An existing non-Beads config must receive the brief too.
            hooks_path.write_text(json.dumps({'hooks': {'Stop': [
                {'hooks': [{'type': 'command', 'command': 'echo custom-only'}]}]}}))
            install()
            custom_hooks = json.loads(hooks_path.read_text())['hooks']
            custom_commands = [h['command'] for groups in custom_hooks.values()
                               for g in groups for h in g['hooks']]
            self.assertIn('echo custom-only', custom_commands)
            self.assertEqual(sum('scripts/brief.sh' in c for c in custom_commands), 1)
            (project / 'scripts/brief.sh').write_text('test "$1" = --hook && echo fixture-brief\n')
            nested = project / 'nested directory'
            nested.mkdir()
            self.assertEqual(subprocess.check_output(brief[0], shell=True, cwd=nested, text=True).strip(), 'fixture-brief')


if __name__ == '__main__':
    unittest.main()
