#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate Codex agents and skill links from the shared harness.

    python3 scripts/codex-support.py write
    python3 scripts/codex-support.py check   # read-only drift check

Agent prompts and skills stay in .claude/. Codex inherits its host's model;
Claude model aliases and tool allowlists are not Codex configuration fields.
"""

import argparse
import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MARKER = "Generated by scripts/codex-support.py"


def agent_text(source, root):
    match = re.fullmatch(r"---\n(.*?)\n---\n(.*)", source.read_text(), re.S)
    if not match:
        raise ValueError(f"{source}: missing agent frontmatter")
    fields = dict(re.findall(r"^([A-Za-z_]+):[ \t]*(.*)$", match[1], re.M))
    values = {key: fields[key] for key in ("name", "description")}
    header = f"# {MARKER} from {source.relative_to(root)}.\n"
    metadata = "\n".join(
        f"{key} = {json.dumps(value, ensure_ascii=False)}"
        for key, value in values.items()
    )
    prompt = "\n".join(json.dumps(line, ensure_ascii=False)[1:-1]
                       for line in match[2].lstrip("\n").split("\n"))
    return header + metadata + '\ndeveloper_instructions = """\n' + prompt + '"""\n'


def artifacts(root):
    sources = sorted((root / ".claude/agents").glob("*.md"))
    skills = sorted((root / ".claude/skills").glob("*/SKILL.md"))
    if not sources or not skills:
        raise ValueError("shared agents and skills must exist under .claude/")
    files = {root / ".codex/agents" / f"{p.stem}.toml": agent_text(p, root)
             for p in sources}
    links = {root / ".agents/skills" / p.parent.name: p.parent for p in skills}
    return files, links


def orphans(root, files):
    return [p for p in (root / ".codex/agents").glob("*.toml")
            if p not in files and MARKER in p.read_text()]


def orphan_links(root, links):
    shared = (root / ".claude/skills").resolve()
    return [p for p in (root / ".agents/skills").glob("*")
            if p not in links and p.is_symlink() and p.resolve().parent == shared]


def check(root=ROOT):
    files, links = artifacts(root)
    problems = [f"{p.relative_to(root)} differs from the shared harness"
                for p, text in files.items() if not p.is_file() or p.read_text() != text]
    problems += [f"{p.relative_to(root)} must link to {target.relative_to(root)}"
                 for p, target in links.items()
                 if not p.is_symlink() or p.resolve() != target.resolve()]
    problems += [f"{p.relative_to(root)} has no source" for p in orphans(root, files)]
    problems += [f"{p.relative_to(root)} has no shared skill" for p in orphan_links(root, links)]
    for problem in problems:
        print(f"  CODEX {problem}")
    if problems:
        print("        run python3 scripts/codex-support.py write")
        return 1
    print(f"  ok    {len(files)} Codex agents and {len(links)} skill links")
    return 0


def write(root=ROOT):
    files, links = artifacts(root)
    # A copied skill may contain local work. Replacing it is a migration for a
    # person to review, never an incidental effect of refreshing an agent.
    for p in links:
        if p.exists() and not p.is_symlink():
            raise ValueError(f"{p}: reconcile the copied skill before replacing it with a link")
    for p, text in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    for p, target in links.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        if p.is_symlink():
            p.unlink()
        p.symlink_to(os.path.relpath(target, p.parent), target_is_directory=True)
    for p in orphans(root, files) + orphan_links(root, links):
        p.unlink()
    return check(root)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("write", "check"))
    args = parser.parse_args()
    try:
        raise SystemExit(check() if args.action == "check" else write())
    except (OSError, ValueError, KeyError) as error:
        parser.exit(1, f"Codex support: {error}\n")
